//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xyDroidFolder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xyDroidFolder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string App_Exit {
            get {
                return ResourceManager.GetString("App_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android file tool.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clipboard_icon {
            get {
                object obj = ResourceManager.GetObject("clipboard-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download succeed: .
        /// </summary>
        internal static string Download_succeed_msg {
            get {
                return ResourceManager.GetString("Download_succeed_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error_msg {
            get {
                return ResourceManager.GetString("Error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string FileBtn_Download {
            get {
                return ResourceManager.GetString("FileBtn_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string FileBtn_Upload {
            get {
                return ResourceManager.GetString("FileBtn_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_star_icon {
            get {
                object obj = ResourceManager.GetObject("folder-star-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get folder succeed.
        /// </summary>
        internal static string Get_folder_succeed_msg {
            get {
                return ResourceManager.GetString("Get_folder_succeed_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting folder content ....
        /// </summary>
        internal static string Getting_folder_content_msg {
            get {
                return ResourceManager.GetString("Getting_folder_content_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to get initial folder content.
        /// </summary>
        internal static string InitFolderNode {
            get {
                return ResourceManager.GetString("InitFolderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive progress：.
        /// </summary>
        internal static string Receive_file_progress {
            get {
                return ResourceManager.GetString("Receive_file_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received File: .
        /// </summary>
        internal static string Received_File {
            get {
                return ResourceManager.GetString("Received_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request download ...: .
        /// </summary>
        internal static string Request_download {
            get {
                return ResourceManager.GetString("Request_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request upload ...: .
        /// </summary>
        internal static string Request_upload {
            get {
                return ResourceManager.GetString("Request_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan this QR to connect.
        /// </summary>
        internal static string ScanTitle {
            get {
                return ResourceManager.GetString("ScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send progress: .
        /// </summary>
        internal static string Send_file_progress {
            get {
                return ResourceManager.GetString("Send_file_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent clipboard text.
        /// </summary>
        internal static string Sent_clipboard_text_msg {
            get {
                return ResourceManager.GetString("Sent_clipboard_text_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text received and putted to clipboard: .
        /// </summary>
        internal static string Text_received_msg {
            get {
                return ResourceManager.GetString("Text_received_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatching clipborad. Click to stop.
        /// </summary>
        internal static string tsbClipboardWatch_tooltip_inWatch {
            get {
                return ResourceManager.GetString("tsbClipboardWatch_tooltip_inWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to start send and receive clipboard content.
        /// </summary>
        internal static string tsbClipboardWatch_tooltip_notWatch {
            get {
                return ResourceManager.GetString("tsbClipboardWatch_tooltip_notWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder of received file.
        /// </summary>
        internal static string tsbOpenReceiveFolder_tooltip {
            get {
                return ResourceManager.GetString("tsbOpenReceiveFolder_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh current node content.
        /// </summary>
        internal static string tsbRefreshCurrentNode_tooltip {
            get {
                return ResourceManager.GetString("tsbRefreshCurrentNode_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload succeed: .
        /// </summary>
        internal static string Upload_succeed_msg {
            get {
                return ResourceManager.GetString("Upload_succeed_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon xyfolder {
            get {
                object obj = ResourceManager.GetObject("xyfolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
